/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2023-05-26

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f0xx.h"
#include "USART_DMA_setup.h"
#include "ADC_setup.h"



/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/

void Adjust_TRGO(uint8_t* data) {
	TIM15->CR1 &= ~TIM_CR1_CEN;
	TIM15->PSC = 200 + 200*(*data); //adjust frequency of TFGO
	TIM15->CR1 |= TIM_CR1_CEN;      //by random law
}

void Turn_on_off_ADC(uint8_t* data) {
	if(*data == 1)
		ADC_start_conversation();   //if in data 1 -> start work ADC
	if(*data == 0)
		ADC_stop_conversation();    //if in data 0 -> stop work ADC
}

void Transfer_amount_of_data_to_PC(uint8_t* data) {
	DMA1_Channel1->CNDTR = *data;      //write in CNDTR amount of data needed in PC
	DMA1_Channel1->CCR |= DMA_CCR_EN;  //and start transfer
}

void Transfer_infinite_data_to_PC(uint8_t* data) {
	if(*data == 1) {
		DMA1_Channel1->CCR |= DMA_CCR_CIRC;           //turn on circular mode for "infinite" transfer of data
		DMA1_Channel1->CNDTR = SIZE_OF_TRANSMIT_DATA;
		DMA1_Channel1->CCR |= DMA_CCR_EN;			  //turn on DMA
	}
	if(*data == 0) {
		DMA1_Channel1->CCR &= ~ DMA_CCR_EN;
		DMA1_Channel1->CNDTR = SIZE_OF_TRANSMIT_DATA;
		DMA1_Channel1->CCR &= ~DMA_CCR_CIRC;
	}
}

void check_command() {
	if(Buffer_empty(&Receive_buf)) //if buffer with command empty -> return
		return;
    //get command by reading 2 first byte and using XOR, for instance 0xAB01 ^ 0xAB00(SYNC_BYTE) = 0x01
	uint16_t command = ((Buffer_get_from_front(&Receive_buf) << 8) | Buffer_get_from_front(&Receive_buf)) ^ SYNC_BYTE;
	uint8_t data = Buffer_get_from_front(&Receive_buf); //get received data for implement some sort of actions

	switch(command) {
		case ADJUST_TRGO:
			Adjust_TRGO(&data);
			break;
		case TURN_ON_OFF_ADC:
			Turn_on_off_ADC(&data);
			break;
		case TRANSFER_CERTAIN_AMOUNT_OF_DATA_TO_PC:
			Transfer_amount_of_data_to_PC(&data);
			break;
		case TRANSFER_INFINITE_AMOUNT_OF_DATA_TO_PC:
			Transfer_infinite_data_to_PC(&data);
			break;
	}

	Clear_buffer(&Receive_buf);  //clear buffer just in case to get new correct command
}

void setup_periphery() {
	InitBuffer(&Receive_buf, (uint16_t*)&rec_arr[0], RECEIVE_BUF_SIZE);
	setup_USART_DMA((uint32_t)(&Receive_buf.buf[0]));
	Setup_periphery_for_ADC();
}

int main(void)
{
	setup_periphery();
	start_receive_data_from_PC();
	while (1)
	{
		check_command();
	}
}



















